name    'scottyc-ucpconfig'
version '0.1.0'

author 'scottyc'
summary 'ucpconfig module'
description 'ucpconfig module'
project_page 'https://stash.healthdirect.org.au/projects/puppet/repos/scottyc-ucpconfig'

# Add dependencies here, if any (NB: Must be in the form 'author/modulename')
#dependency 'puppetlabs/stdlib', '>= 2.0.0'
